version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: konstructify-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: konstructify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d konstructify"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    image: node:18-bullseye
    container_name: konstructify-web
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      CHOKIDAR_USEPOLLING: "1"
      DATABASE_URL: postgres://postgres:postgres@db:5432/konstructify
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: dev-secret
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    command: sh -c "apt-get update && apt-get install -y --no-install-recommends openssl ca-certificates && rm -rf /var/lib/apt/lists/* && npm install && npx drizzle-kit generate && npx drizzle-kit push && npx next dev -H 0.0.0.0 -p 3000"

volumes:
  postgres_data:
  node_modules:
  next_cache:
